---
title: "Summarizing covid-19 situation from 1.10.20 to 31.01.21"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r}
##################
#### Project SMSD
##################

library(ggplot2)


#load data 
df_global <- data.frame(read.csv("https://raw.githubusercontent.com/pcm-dpc/
COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv"))

#read data we are interested in
#then those that are relative to the following coupla of parameters:
#regione: Sicilia
#data:  1st October 2020 to 1st February 2021 
df_sicily_secondwave <- df_global[which(df_global$denominazione_regione == "Sicilia" & (df_global$data >= "2020-09-30T10:00:00" & df_global$data <= "2021-02-01T10:00:00")), ]
#df_em <-df_global[which(df_global$denominazione_regione == "Emilia-Romagna" & (df_global$data >= "2021-10-01T10:00:00" & df_global$data <= "2022-01-01T10:00:00")), ]

################
# clean dataset 
################

# remove unuseful columns
df <- df_sicily_secondwave[ , -which(names(df_sicily_secondwave) %in% c("stato", "codice_regione", "denominazione_regione", "lat", "long", "note"))]
df <- df[ , -c(17:24)]


# add column accounting for the number of new swabs carried out
for(x in 2:nrow(df)) {
  df$nuovi_tamponi[x] <- df$tamponi[x] - df$tamponi[x-1] 
}

# add column for new death per day
for(x in 2:nrow(df)){
 df$nuovi_deceduti[x] <- df$deceduti[x] - df$deceduti[x-1] 
}

for(x in 2:nrow(df)){
 df$nuovi_ricoveri[x] <- df$ricoverati_con_sintomi[x] - df$ricoverati_con_sintomi[x-1] 
}

for(x in 2:nrow(df)){
 df$nuove_intensive[x] <- df$terapia_intensiva[x] - df$terapia_intensiva[x-1] 
}


df$ricoverati_con_sintomi
df$nuovi_deceduti
# remove first row
df <- df[-1,]

#index reordering
row.names(df) <- NULL       

#add color
df$color <-NA
df$color[1:36]<-"bianco"
df$color[c(37:59, 89:91, 101:108)]<-rep("arancione",34)
df$color[c(60:84,99,100)]<-rep("giallo",27)
df$color[c(85:88,92:95,96,97,98, 109:123)]<-rep("rosso",25)


############################
### 1.Perform some explanatory analysis for your data, especially by use of graphical tools.
############################

df$data <- as.Date(df$data,  "%Y-%m-%d")
# see how the number of positives changes over time
ggplot() +
  geom_line(data = df, aes(x = data, y = nuovi_positivi, color="nuovi positivi", group = 1)) +
  geom_point(data = df, aes(x = data, y = nuovi_positivi, color="nuovi positivi", group = 1))+ 
  labs(x = "Time", y = "New positives") +
  scale_x_date(date_breaks = '5 days',
               date_labels = '%Y-%m-%d') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# see how the number of swabs carried out changes over time
ggplot() +
  geom_line(data = df, aes(x = data, y = tamponi, group = 1)) +
  geom_point(data = df, aes(x = data, y = tamponi, group = 1)) +
  labs(x = "Time", y = "Swabs") +
  scale_x_date(date_breaks = '5 days',
               date_labels = '%Y-%m-%d') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#########################
### 2.Describe the quality of the data and discuss whether and how a plausible statistical model could be posed.
#########################

# check for missing values in the data frame
na_count <- sapply(df, function(y) sum(length(which(is.na(y)))))
na_count <- data.frame(na_count)

```
1) Some useful analysis, correlation and plots about covid data from 1/10/20 to 31/01/21 


```{r}
    plotPositiveDeath <- ggplot() +
    geom_line(data = df, aes(x = data, y = (nuovi_deceduti/nuovi_positivi)*100, color="rapporto percentuale tra deceduti e positivi", group = 1)) +
    labs(x = "Time", y = "% ratio of positive to deceased", title = "Fatality rate") +
    scale_x_date(date_breaks = '5 days',
                 date_labels = '%Y-%m-%d') +
    #scale_y_continuous(limits = c(0,100))+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none", plot.title = element_text(hjust = 0.5))
  
  plotPositiveDeath
```





```{r}

  plotPositiveSwabs <- ggplot() +
    geom_line(data = df, aes(x = data, y = (nuovi_positivi/nuovi_tamponi)*100, color="rapporto percentuale tra deceduti e positivi", group = 1)) +
    labs(title = "Positivity rate", x = "Time", y = "% ratio of tested swabs to positives") +
    scale_x_date(date_breaks = '5 days',
                 date_labels = '%Y-%m-%d') +
    #scale_y_continuous(limits = c(0,100))+ 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none", plot.title = element_text(hjust = 0.5))
  plotPositiveSwabs
```



```{r}
    theme_set(theme_bw())
    plotIntensive <- ggplot() +
    geom_line(data = df, aes(x = data, y = terapia_intensiva, color="Places occupied in intensive care", group = 1)) +
    geom_line(data = df, aes(x = data, y = ricoverati_con_sintomi, color="hospitalised with symptoms", group = 1)) +
    labs(title = "Hospitalised and places occupied in intensive terapy", x = "Time", y = "Number of places occupied") +
    scale_x_date(date_breaks = '5 days',
                 date_labels = '%Y-%m-%d') +
    #scale_y_continuous(limits = c(0,100))+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(hjust = 0.5))
  plotIntensive
```


```{r}
plotSummary <- ggplot() +
    geom_line(data = df, aes(x = data, y = nuovi_positivi, color="Positives", group = 1))+
    geom_line(data = df, aes(x = data, y = nuovi_deceduti, color="Deaths", group = 1))+
    geom_line(data = df, aes(x = data, y = nuove_intensive, color="Intensive care", group = 1))+
    geom_line(data = df, aes(x = data, y = nuovi_ricoveri, color="Hospitalised with symptoms", group = 1)) +
    labs(title = "Summary of covid situation between 1/10/20 and 31/02/21", x = "Time", y = "Cases") +
    scale_x_date(date_breaks = '5 days',
                 date_labels = '%Y-%m-%d') +
    #scale_y_continuous(trans = "log10")+
    #scale_y_continuous(limits = c(0,100))+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(hjust = 0.5))

plotSummary


```




```{r}
plotOtherSummary <- ggplot() +
    geom_line(data = df, aes(x = data, y = totale_positivi, color="Positives", group = 1))+
    geom_line(data = df, aes(x = data, y = deceduti, color="Deaths", group = 1))+
    geom_line(data = df, aes(x = data, y = terapia_intensiva, color="Intensive care", group = 1))+
    geom_line(data = df, aes(x = data, y = ricoverati_con_sintomi, color="Hospitalised with symptoms", group = 1)) +
    labs(title = "Summary of covid situation between 1/10/20 and 31/02/21", x = "Time", y = "Cases") +
    scale_x_date(date_breaks = '5 days',
                 date_labels = '%Y-%m-%d') +
    scale_y_continuous(trans = "log10")+
    #scale_y_continuous(limits = c(0,100))+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(hjust = 0.5))
plotOtherSummary
```

```{r}

model_0 <- lm(nuovi_positivi ~ nuovi_deceduti + nuovi_ricoveri, data = df)

plot(model_0)

model_1 <- loess(nuovi_positivi ~ nuovi_deceduti + nuovi_ricoveri + isolamento_domiciliare, data = df, span = 0.90)

smoothed_1 <- predict(model_1)

smoothed_1
df$nuovi_positivi

ggplot() + 
  geom_point(data = df, aes(x = data, y = smoothed_1, color="Model", group = 1)) +
  geom_line(data = df, aes(x = data, y = smoothed_1, color="Model", group = 1)) +
  geom_point(data = df, aes(x = data, y = nuovi_positivi, color="Real", group = 1)) +
  geom_line(data = df, aes(x = data, y = nuovi_positivi, color="Real", group = 1)) +
  labs(title = "Model_V1", x = "Time", y = "Cases") +
    scale_x_date(date_breaks = '5 days',
                 date_labels = '%Y-%m-%d') +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), plot.title = element_text(hjust = 0.5))
  
plot(smoothed_1)
```



