---
title: "COVID-19-sicilia-second-wave"
author: "Francesco Ortu"
date: "1/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data analysis

```{r import data}
setwd("/home/francesco/Repository/SMDS")
df <- data.frame(read.csv("covid.sicilia.clean.csv"))
df <- df[,-c(1,2)]

```

```{r summary}
summary(df)
```

```{r plot, echo=FALSE}
library(ggplot2)
df$data <- as.Date(df$data)
nuovi_positivi <- ggplot() +
  geom_line(data = df, aes(x = data, y = nuovi_positivi, color="nuovi positivi", group = 1)) +
  geom_point(data = df, aes(x = data, y = nuovi_positivi, color="nuovi positivi", group = 1))+ 
  labs(x = "Time", y = "New positives") +
  scale_x_date(date_breaks = '5 days',
               date_labels = '%Y-%m-%d') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# see how the number of swabs carried out changes over time
tamponi<-ggplot() +
  geom_line(data = df, aes(x = data, y = nuovi_tamponi, group = 1,  color=color)) +
  geom_point(data = df, aes(x = data, y = nuovi_tamponi, group = 1,   color=color)) +
  labs(x = "Time", y = "Swabs") +
  scale_x_date(date_breaks = '5 days',
               date_labels = '%Y-%m-%d') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_color_manual(values=c("orange","white","yellow", "red"))


# show the total number of hospitalized 
ospedalizzati<-ggplot() +
  geom_line(data = df, aes(x = data, y = totale_ospedalizzati, group = 1,  color=color)) +
  geom_point(data = df, aes(x = data, y = totale_ospedalizzati, group = 1,   color=color)) +
  labs(x = "Time", y = "hospitalized") +
  scale_x_date(date_breaks = '5 days',
               date_labels = '%Y-%m-%d') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_color_manual(values=c("orange","white","yellow", "red"))

# show the total number of deaths 
morti<-ggplot() +
  geom_line(data = df, aes(x = data, y = nuovi_deceduti, group = 1,  color=color)) +
  geom_point(data = df, aes(x = data, y = nuovi_deceduti, group = 1,   color=color)) +
  labs(x = "Time", y = "deaths") +
  scale_x_date(date_breaks = '5 days',
               date_labels = '%Y-%m-%d') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_color_manual(values=c("orange","white","yellow", "red"))
nuovi_positivi
tamponi
ospedalizzati
morti
```

Correlation analysis:

```{r correlation, echo =FALSE}
library("ggcorrplot")
corr <- cor_pmat(df[,2:15, 17])
ggcorrplot(corr)
nuovi_positivi_storiche <- df[,c(1,8)]
positivi_storiche<-ts(nuovi_positivi_storiche$nuovi_positivi, start = 2020/10/01, frequency=1)
acf(positivi_storiche)
```
```{r}

```

